from .vehicle_all_list_api_view import VehicleAllListAPIView
from .vehicle_all_retrieve_api_view import VehicleAllRetrieveAPIView
from .vehicle_user_create_api_view import VehicleUserCreateAPIView
from .vehicle_user_delete_api_view import VehicleUserDeleteAPIView
from .vehicle_user_list_api_view import VehicleUserListAPIView
from .vehicle_user_update_api_view import VehicleUserUpdateAPIView
