# Generated by Django 5.0.7 on 2024-08-04 00:11

import stores.models.vehicle
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to=stores.models.vehicle.image_upload_to),
        ),
    ]
