# Generated by Django 5.0.7 on 2024-08-04 00:11

from django.db import migrations, models

import backend.stores.models.vehicle


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(
                upload_to=backend.stores.models.vehicle.image_upload_to
            ),
        ),
    ]
