# Generated by Django 5.0.7 on 2024-08-04 13:21

import backend.stores.models.vehicle
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.stores.models.vehicle.image_upload_to),
        ),
    ]
